######################################################################
# Automatically generated by qmake (2.01a) Paz Mar 6 23:57:57 2011
######################################################################

TEMPLATE = app
TARGET = cdarsiv
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += anaPencere.h
FORMS += anaPencere.ui
SOURCES += anaPencere.cpp main.cpp
RESOURCES += ikonlar.qrc
QT += sql
